In [1]:
import numpy as np

In [2]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr = np.array(lista)

In [4]:
type(arr)

numpy.ndarray

In [5]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Indexing
Acceder a los por medio de su índice

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[0]

1

In [9]:
arr[0] + arr[5]

7

In [10]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
matriz[0]

array([1, 2, 3])

In [12]:
matriz[0,2]

3

## Slicing

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr[2:6]

array([3, 4, 5, 6])

In [19]:
arr[::2]

array([1, 3, 5, 7, 9])

In [20]:
arr[-3:]

array([7, 8, 9])

In [21]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [23]:
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])