In [40]:
import numpy as np

In [41]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

Analizar si los elementos del array son mayores que devuelve un array con verdadero o falso

In [42]:
condicion = arr > 5
condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Se obtiene el resultado aplicando la condición accediendo al índice

In [43]:
arr[condicion]

array([ 6,  7,  8,  9, 10], dtype=int8)

Se puede aplicar operadores para añadir más condiciones

In [44]:
arr[(condicion) & (arr < 9)]

array([6, 7, 8], dtype=int8)

Reasignar valores a elementos que cumplan una condición en un array

In [45]:
arr[arr > 6] = 99
arr

array([ 1,  2,  3,  4,  5,  6, 99, 99, 99, 99], dtype=int8)

## Challenge
Crear un tensor de 3 dimensiones con 3 matrices de 10 * 10 y valores aleatorios entre 4 y 400. Hacer un slice de los 60 últimos valores de la matriz 3 del segundo ejemplo y cambiar los valores que sean mayores de 200 a 1.

- crear una matriz de 10 * 10
- crear un tensor con 3 matrices
- seleccionar los 60 últimos valores de la última matriz
- cambiar los valores que cumplan una condición

In [120]:
def randomMatriz():
    vector = np.random.randint(4,400,(10*10))
    np.array(vector)
    return vector
tensor = np.array([[randomMatriz(), randomMatriz(), randomMatriz()], [randomMatriz(), randomMatriz(), randomMatriz()], [randomMatriz(), randomMatriz(), randomMatriz()]])

print('dimensions: ', tensor.ndim)
print(tensor)

dimensions:  3
[[[253 115 299 262 200 337 257 123  83 247 143  92 209 240  94 114  36
   304 288  79 307   5 315 324  90 190  65 161 114 317 268 228 111 102
   224 357 152  82  72 175 291 346 344 224 320 367 376 370 146 195 259
   229 231 395  63 183 270 203 357 249  20 296 195 327  71 103 227 119
   159 225 207  48 218 194 199 359 105 242 372 292  42  72 317 385 317
   257 388 100 307 351 376 148 266  51 250   9 243 260 239 258]
  [  6  53 287  45  11 212 249 350 234 190  56 164 241 318 298 144 377
    27 397  86 352 163 330 243 159 273  80  11  13 211 144 328 289 153
   165 209 359 380  45 290 291  15 383 248   7 374  71 327 238 336 117
   229 389  45 325 143  94 333 128 196 134 396 100 321  15 171 181  31
    65 226 213 287 212 266 242  79 318 256 141 207  92 243  82 170 219
   303  38 282 114 130  40 338 231 255 152 260 342 261 357 215]
  [306 162 234  37 294 393  17 144 188 247  24 343 112 360 325 324  11
   373 123 163 363 267 371 246 222  29 242 382 154 170 163 220  77  97
   27

In [134]:
tensor_copy = tensor[-1][-1]
last_tensor = tensor_copy[60:]
last_tensor[last_tensor > 200] = 1
print(last_tensor)

[173   1   1  65  60 142   1   1   1 186  31   4   1  26   1  30   1  29
   1   1  47   1   1   1   1  77 163  66 154 163  56  48 155  72 180  38
   1 108   1   1]


In [133]:
last_tensor.size
last_tensor.reshape(8,5)

array([[173,   1,   1,  65,  60],
       [142,   1,   1,   1, 186],
       [ 31,   4,   1,  26,   1],
       [ 30,   1,  29,   1,   1],
       [ 47,   1,   1,   1,   1],
       [ 77, 163,  66, 154, 163],
       [ 56,  48, 155,  72, 180],
       [ 38,   1, 108,   1,   1]])