# copy

In [1]:
import numpy as np

In [14]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Seleccionar un trozo de un array

In [15]:
sliced_arr = arr[0:6]
sliced_arr

array([0, 1, 2, 3, 4, 5])

Cambiar todos los valores de un array a 0

In [9]:
sliced_arr[:] = 0
sliced_arr

array([0, 0, 0, 0, 0, 0])

De esta forma los valores del array original se modifican porque la variable apunta a la misma referencia en memoria

In [7]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

La función .copy() copia los datos de un array en otro espacio en memoria diferente

In [16]:
sliced_arr_copy = sliced_arr.copy()
sliced_arr_copy[:] = 100
print('sliced array:' ,sliced_arr)
print('sliced array copy:' ,sliced_arr_copy)

sliced array: [0 1 2 3 4 5]
sliced array copy: [100 100 100 100 100 100]
