## Dimensiones

In [2]:
import numpy as np

### Scalar

In [4]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

### Vector

In [8]:
vector = np.array([1, 2, 3])
print(vector)
vector.ndim

[1 2 3]


1

### Matriz

In [12]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
matrix.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

### Tensor 3D

In [4]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

### Tensor 4D

In [20]:
tensor4d = np.array([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]], [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]])
print(tensor4d)
tensor4d.ndim

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]


 [[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]]


4

## Agregar o eliminar dimensiones

In [25]:
vector = np.array([1, 2, 3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

- Agregar una dimensión en la misma fila

In [24]:
expand = np.expand_dims(np.array([1, 2, 3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

- Eliminar dimesnsiones no usadas

In [27]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


## Challenge

In [55]:
arr = np.array(['1', '2', 3], dtype='int8')
print(arr)
print(arr.ndim)
print(arr.dtype)
matrix = np.expand_dims(arr, axis=0)
print(matrix)
print(matrix.ndim)
print(matrix.dtype)
tensor = np.expand_dims(matrix, axis=0)
print(tensor)
print(tensor.ndim)
print(tensor.dtype)
sqz = np.squeeze(tensor)
sqz = sqz.astype(np.string_)
print(sqz)
print(sqz.ndim)
print('sqz type:', sqz.dtype)



[1 2 3]
1
int8
[[1 2 3]]
2
int8
[[[1 2 3]]]
3
int8
[b'1' b'2' b'3']
1
sqz type: |S4
