# Funciones principales de Numpy

In [1]:
import numpy as np

In [12]:
vector = np.random.randint(1, 20, 10)
print(vector)

[ 2  9  1  3  3 18  6  8  7 13]


In [13]:
matriz = vector.reshape(2,5)
matriz

array([[ 2,  9,  1,  3,  3],
       [18,  6,  8,  7, 13]])

## Max
La función .max() devuelve el valor más alto de un vector

In [8]:
matriz.max()

17

La función .max(#) devuelve el valor más alto de una matriz en el eje #
- '#' = 0 = eje x
- '#' = 1 = eje y

In [9]:
matriz.max(0)

array([ 8, 12, 17, 11,  8])

In [10]:
matriz.max(1)

array([17, 17])

La función .argmax() en un vector devuelve el menor índice del valor más alto

In [14]:
vector.argmax()

5

La función .argmax(#) en una matriz devuelve el menor índice del valor más alto en el eje y

In [15]:
matriz.argmax(0)

array([1, 0, 1, 1, 1], dtype=int64)

## Min
Las funciones .min() y .argmin() actúan con los números mínimos  

In [16]:
vector.min()

1

In [22]:
vector.argmin()

2

In [19]:
matriz.min()

1

In [20]:
matriz.min(0)

array([2, 6, 1, 3, 3])

In [21]:
matriz.min(1)

array([1, 6])

In [23]:
matriz.argmin()

2

In [24]:
matriz.argmin(0)

array([0, 1, 0, 0, 0], dtype=int64)

In [26]:
matriz.argmin(1)

array([2, 1], dtype=int64)

## Peak to peak
La función .ptp() devuelve la diferencia entre el valor más alto y el más bajo

In [27]:
vector

array([ 2,  9,  1,  3,  3, 18,  6,  8,  7, 13])

In [28]:
vector.ptp()

17

In [29]:
matriz

array([[ 2,  9,  1,  3,  3],
       [18,  6,  8,  7, 13]])

In [30]:
matriz.ptp()

17

In [31]:
matriz.ptp(0)

array([16,  3,  7,  4, 10])

In [32]:
matriz.ptp(1)

array([ 8, 12])

## Percentile
- np.percentile(arr, 50) devuelve la mediana, el valor de la mitad o la división de los valores de la mitad
- np.percentile(arr, 100) devuelve el valor más alto del rango
- np.percentile(arr, 0) devuelve el valor más bajo del rango

In [35]:
np.percentile(vector, 50)

6.5

In [36]:
np.percentile(vector, 0)

1.0

In [37]:
np.percentile(vector, 100)

18.0

## Mediana
np.median(arr) devuelve la mediana

In [38]:
np.median(vector)

6.5

In [39]:
np.median(matriz, 0)

array([10. ,  7.5,  4.5,  5. ,  8. ])

## Desviación standard
np.std(arr) devuelve la desviación standard

In [40]:
np.std(vector)

5.059644256269407

## Varianza
np.var(arr) devuelve la varianza

In [41]:
np.var(vector)

25.6

np.std(arr) ** 2 es la varianza

In [42]:
np.std(vector) ** 2

25.6

## Media
np.mean(arr) devuelve la media

In [43]:
np.mean(vector)

7.0