In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

In [3]:
lista * 2

[1, 2, 1, 2]

In [6]:
arr = np.arange(0,10)
print(arr)
arr2 = arr.copy()
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


## Operaciones

Los arrays creados con numpy permiten las operaciones por cada uno de los elementos solo con la declaraión de la operación

In [7]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [9]:
arr / 1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Cuando no se puede realizar una operación con un elemento, como dividir por cero, numpy devuelve un warning con el error para el elemento en concreto y realiza la operación con los elementos con los que sí puede realizarla

In [11]:
result = 1 / arr
result

C:\Users\Caesar\AppData\Local\Temp\ipykernel_56920\3289119542.py:1: RuntimeWarning: divide by zero encountered in divide
  result = 1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [12]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
arr / arr2

C:\Users\Caesar\AppData\Local\Temp\ipykernel_56920\1444868932.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [21]:
matriz = arr.reshape(2,5)
print(matriz.ndim)
matriz

2


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
matriz2 = matriz.copy()
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

## Producto punto o Producto escalar
- producto de una matriz fila y una matriz columna
- matriz
- matriz transpuesta

In [22]:
matriz.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [23]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [24]:
np.matmul(matriz.T, matriz2)

array([[25, 30, 35, 40, 45],
       [30, 37, 44, 51, 58],
       [35, 44, 53, 62, 71],
       [40, 51, 62, 73, 84],
       [45, 58, 71, 84, 97]])

In [25]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])