## Shape and reshape

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 10, (3,2))

La propiedad .shape devuelve la estructura del array en filas y columnas

In [3]:
arr.shape

(3, 2)

La propiedad .reshape(#,#) restructura el array en #*# 

In [4]:
arr

array([[3, 1],
       [8, 8],
       [2, 3]])

In [5]:
reshapedArr = arr.reshape(2,3)
reshapedArr

array([[3, 1, 8],
       [8, 2, 3]])

In [6]:
reshapedArr.shape

(2, 3)

np.reshape(arr,(1,6)) restructura arr

In [7]:
np.reshape(reshapedArr, (2,3))

array([[3, 1, 8],
       [8, 2, 3]])

np.reshape(arr,(1,6), 'C') restructura arr con order='C', lo que significa que irá en orden por filas, como lo hace el lenguaje C

In [8]:
np.reshape(reshapedArr, (3,2), 'C')

array([[3, 1],
       [8, 8],
       [2, 3]])

np.reshape(arr,(1,6), 'F') restructura arr con order='F', lo que significa que irá en orden por columnas, como lo hace el lenguaje Fortran

In [9]:
np.reshape(reshapedArr, (3,2), 'F')

array([[3, 2],
       [8, 8],
       [1, 3]])

np.reshape(arr,(1,6), 'F') restructura arr con order='A', lo que significa que tomará el order que esté más optimizado en la ma´quina actual

In [10]:
np.reshape(reshapedArr, (3,2), 'A')

array([[3, 1],
       [8, 8],
       [2, 3]])

Es más legible el order de tipo C, además de que es la base de Python