In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [3]:
arr.dtype

dtype('int32')

## Cambiar tipo de dato
- Solo se define un tipo de dato en cada array
- https://numpy.org/doc/stable/user/basics.types.html

In [4]:
arr = np.array([1, 2, 3, 4], dtype='float64')
arr.dtype

dtype('float64')

In [5]:
arr

array([1., 2., 3., 4.])

- También se puede cambiar el tipo de dato con la función astype(np.tipodedato)

In [9]:
arr = np.array([0, 2, 3, 4])
arr

array([0, 2, 3, 4])

In [10]:
arr = arr.astype(np.float64)
arr

array([0., 2., 3., 4.])

In [12]:
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True])

In [13]:
arr = arr.astype(np.string_)
arr

array([b'False', b'True', b'True', b'True'], dtype='|S5')

In [14]:
arr = np.array(['0', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

array([0, 2, 3, 4], dtype=int8)